Lint

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -17,9 +17,9 @@ download_release "$ASDF_INSTALL_VERSION" "$release_file"
 
 #  Extract contents of zip file into the download directory
 if ! type "unzip" &>/dev/null; then
-    echo "ERROR: Command 'unzip' not found."
-    echo "unzip must be installed on your system."
-    exit 1
+	echo "ERROR: Command 'unzip' not found."
+	echo "unzip must be installed on your system."
+	exit 1
 fi
 unzip -q "$release_file" -d "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
 
